version: '3'
services:
  webapp-service:
    image: node:10-slim
    container_name: nfe-visual
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command:
      sh -c 'npm run serve'
    ports:
      - "8080:8080"
