apiVersion: v1
kind: Service
metadata:
  name: servico-nfe-visual
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: nfe
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  externalIPs:
    - 138.197.237.233
